domain: example.com
url: https://example.com
baseurl: "/wind"

title: TRI
email: theromanivy@gmail.com
author: Ivy Roman

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "theromanivy@gmail.com"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
